// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmqhj97ABxVjoIN22VyKiUUXo038tott0',
    appId: '1:724993654144:web:a6dd6d3f9b56902ef75565',
    messagingSenderId: '724993654144',
    projectId: 'bucketlist-app-1f852',
    authDomain: 'bucketlist-app-1f852.firebaseapp.com',
    storageBucket: 'bucketlist-app-1f852.firebasestorage.app',
    measurementId: 'G-EV4F8YQ0ZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbm4XbAJy87U1H1K9_0ymWQfPiiJyMNFY',
    appId: '1:724993654144:android:7b7ae00782f89ffff75565',
    messagingSenderId: '724993654144',
    projectId: 'bucketlist-app-1f852',
    storageBucket: 'bucketlist-app-1f852.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnKOaBfPLFXmg1Hp9dqWgZyHL_SMKM7rY',
    appId: '1:724993654144:ios:7b98f214c9cf1236f75565',
    messagingSenderId: '724993654144',
    projectId: 'bucketlist-app-1f852',
    storageBucket: 'bucketlist-app-1f852.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnKOaBfPLFXmg1Hp9dqWgZyHL_SMKM7rY',
    appId: '1:724993654144:ios:7b98f214c9cf1236f75565',
    messagingSenderId: '724993654144',
    projectId: 'bucketlist-app-1f852',
    storageBucket: 'bucketlist-app-1f852.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmqhj97ABxVjoIN22VyKiUUXo038tott0',
    appId: '1:724993654144:web:ea7e361bff5a76e9f75565',
    messagingSenderId: '724993654144',
    projectId: 'bucketlist-app-1f852',
    authDomain: 'bucketlist-app-1f852.firebaseapp.com',
    storageBucket: 'bucketlist-app-1f852.firebasestorage.app',
    measurementId: 'G-V82X349P6C',
  );
}
